#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------

# Stack initialization
echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
fin project reset -f
echo -e "${green_bg} Step 2 ${NC}${green} Initializing docksal...${NC}"
# This runs inside cli using http://docs.docksal.io/en/v1.4.0/fin/custom-commands/#executing-commands-inside-cli
fin init-site

#install composer
echo -e "${green_bg} Step 3 ${NC}${green} Composer install...${NC}"
composer install

#pull db
echo -e "${green_bg} Step 4 ${NC}${green} Pull DB ${NC}"
fin pull db --yes

#pull files
echo -e "${green_bg} Step 5 ${NC}${green} Pull Files ${NC}"
fin pull files --yes

#install theme npm
echo -e "${green_bg} Step 6 ${NC}${green} Install Theme Dependencies ${NC}"
cd "${DOCROOT_PATH}/themes/vertexinc"
npm install

#rebuild cache
echo -e "${green_bg} Step 7 ${NC}${green} Rebuild Cache! ${NC}"
fin drush cr --yes
fin drush cim --yes
echo -e "${green_bg} BOOYAKASHA ${NC}${green} Completed all initialization steps.${NC}"

#-------------------------- END: Execution --------------------------------
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
fin drush cr --yes