#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------
# Initialize local settings files
reset_docksal_local ()
{

	local template="$1"
	local settings="$2"

	if [[ ! -f $settings ]]; then
		echo "Copying ${template}..."
		cp $template $settings
	else
		echo "removing ${settings}"
		rm $settings
		echo "Copying ${template}..."
		cp $template $settings
	fi
}
# Initialize local settings files
init_settings ()
{
	# Copy from settings templates
	copy_settings_file "${SITEDIR_PATH}/example.settings.local.php" "${SITEDIR_PATH}/settings.local.php"
}

# Fix file/folder permissions
fix_permissions ()
{
	local filesdir="${SITEDIR_PATH}/files"

	if [[ ! -d $filesdir ]]; then
		echo "Creating files directory ${filesdir}"
		mkdir ${SITEDIR_PATH}/files
	else
		echo "Files directory exists"

	fi
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
	echo "Making files directory writable..."
	chmod -R 777 "${SITEDIR_PATH}/files"
}


#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
reset_docksal_local ${PROJECT_ROOT}/.docksal/docksal-local.env.example ${PROJECT_ROOT}/.docksal/docksal-local.env
fix_permissions
init_settings



#-------------------------- END: Execution --------------------------------
