#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin build

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#install theme npm
echo -e "${green_bg} Executing build step ${NC}"
echo -e "${green} Composer install/update ${NC}"
composer install
#install theme npm
echo -e "{green} Install Theme Dependencies ${NC}"
cd "${DOCROOT_PATH}/themes/vertexinc"
npm install
#rebuild cache
echo -e "${green_bg} Step 7 ${NC}${green} Rebuild Cache and Import Config ${NC}"
fin drush cr --yes
fin drush cim --yes


echo -e "${green_bg} BUILD COMPLETE ${NC}"
